apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
  namespace: default
spec:
   ports:
     - port: 3000
       nodePort: 30044
   type: NodePort
   selector:
     app: helloworld
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: react-helloworld:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3000